services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: test
      TZ: Europe/Helsinki
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
     - ssr_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - ssr_net
volumes:
  pg_data_volume:
networks:
  ssr_net:
    external: true
    name: ssr_next_network
