name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
      - master
      - robotfw-tests
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    container:
      image: marketsquare/robotframework-browser:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up Docker Compose
      #   run: |
      #     docker compose version || sudo apt-get update -y && sudo apt-get install -y docker-compose

      - name: Run Robot Framework tests
        run: # |
          # docker compose -f robotfw-docker-compose.yml up --exit-code-from robot
          rfbrowser init
          robot --outputdir results tests

      - name: Upload Robot results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
